const PLAYER_STATUS_NOT_PRESENT = 0;
const PLAYER_STATUS_JOIN = 1;
const PLAYER_STATUS_READY = 2;

module.exports = {
    PLAYER_STATUS_NOT_PRESENT,
    PLAYER_STATUS_JOIN,
    PLAYER_STATUS_READY,
}
